# Generated by Django 5.2.3 on 2025-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smusic',
            fields=[
                ('songid', models.IntegerField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=30)),
                ('moviename', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('singername', models.CharField(max_length=30)),
                ('song', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
