# Generated by Django 5.2.3 on 2025-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smusic',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
