# Generated by Django 5.2.3 on 2025-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_smusic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pmusic',
            fields=[
                ('songid', models.IntegerField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=30)),
                ('moviename', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('singername', models.CharField(max_length=30)),
                ('song', models.FileField(upload_to='songs/')),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
