# Generated by Django 5.2.3 on 2025-07-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_fmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('songid', models.IntegerField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=30)),
                ('moviename', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('singername', models.CharField(max_length=30)),
                ('song', models.FileField(upload_to='songs/')),
                ('image', models.FileField(null=True, upload_to='images/')),
            ],
        ),
    ]
