# Generated by Django 5.2.3 on 2025-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('singerid', models.IntegerField(primary_key=True, serialize=False)),
                ('singername', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='images/')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
    ]
